### ISSUE TITLE
Codigos de colores

### ISSUE THREAD

**Issue by nancysanchezuno** [Fabrizio1996laz/TRIVIA-MTPE#2]
Hola Fabrizio, te recomiendo hacer más atractiva tu trivia añadiéndole colores al titulo y a cada pregunta. Se vera mucho mejor de lo que ya está.
![image](https://user-images.githubusercontent.com/112920082/190875344-603dde0e-6a6a-4ce3-9fa8-f888e6e5e0f9.png)

**Comment by Fabrizio1996laz** [comment]
Hola Nancy, en la trivia he mejorado poniéndole color para que sea más atractivo, y he realizo mejoras como colocar tu nombre y puntuación, espero te sea mas atractivo y así puedan interactuar.

![image](https://user-images.githubusercontent.com/113265534/190944391-3ad2b49f-d5a3-4d09-a6bb-846a5278f4fd.png)

**Comment by nancysanchezuno** [comment]
He podido jugar nuevamente tu trivia Fabrizio y realmente el cambio ha sido positivo. Excelente trabajo, es una trivia muy divertida y personalizada.
