### ISSUE TITLE
Espaciado

### ISSUE THREAD

**Issue by nancysanchezuno** [Fabrizio1996laz/TRIVIA-MTPE#3]
Hola!, te recomiendo reducir el espaciado entre la pregunta y respuesta. 
![image](https://user-images.githubusercontent.com/112920082/190875532-2b111909-cc91-4602-bff6-877990ff9912.png)

**Comment by Fabrizio1996laz** [comment]
Hola Nancy buenas noches, se realizaron las correcciones de los espacios, gracias por tu observación te invito a jugar la trivia.

![image](https://user-images.githubusercontent.com/113265534/190944482-8b4c0aa7-f0e8-4b23-894f-bee2e48081ba.png)

**Comment by nancysanchezuno** [comment]
El espaciado entre pregunta y respuesta se redujo exitosamente, tu trivia se ve mucho más dinámica de lo que ya era.
